name: Ward release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4.0.0
      with:
        python-version: '3.10'
    - uses: snok/install-poetry@v1.3.1
      with:
        virtualenvs-create: true
    - name: Publish to PyPI
      run: |
        poetry publish --build --username __token__ --password ${{ secrets.pypi_api_token }}
      working-directory: ${{ github.workspace }}
